_destructiveTests:
  enabled: true
api:
  extraEnv:
    EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
influxdb2:
  # Needed to set this for the tests to not fail. Possibly related to
  # https://github.com/Flagsmith/flagsmith/issues/340
  enabled: false
