apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels: {{- include "influxdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.influxdb.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "influxdb.selectorLabels" . | nindent 4 }}